import{a as l,S as p,i as m}from"./assets/vendor-a5e83976.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function a(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerpolicy&&(s.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?s.credentials="include":r.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(r){if(r.ep)return;r.ep=!0;const s=a(r);fetch(r.href,s)}})();l.defaults.headers.common["x-api-key"]="live_Pk14S8ulfecIfka8yDfPenVntw4fo66iUbRXOR4TgsU8PRNzV75D5XH54uQrXIvv";const h="https://api.thecatapi.com",g="v1/breeds",v="v1/images/search";function d(t){return l.get(t).then(e=>e.status>=400?new Error(e.statusText):e.data)}function u(t,e=""){return`${h}/${t}${e}`}function y(){const t=u(g);return d(t)}function S(t){const e=new URLSearchParams({breed_ids:t}),a=u(v,`?${e}`);return d(a)}const b={showSearch:!1,placeholderText:"Choose a cat breed"},C={afterChange:I},o={selectWraper:document.querySelector(".select-wraper"),selectBreed:new p({select:".breed-select",settings:b,events:C}),pLoader:document.querySelector(".loader"),divCatInfo:document.querySelector(".cat-info")};function L(t){const e=[{placeholder:!0,text:"Choose a cat breed"}];t.forEach(a=>e.push({text:`${a.name}`,value:`${a.id}`})),o.selectBreed.setData(e),n(o.pLoader,!1),n(o.selectWraper,!0)}function w({url:t,breeds:e}=cat){const a=`
        <img class="image" src="${t}" alt="${e[0].name}" />
        <div class="text-info-block">
            <h2 class="breed-name">${e[0].name}</h2>
            <p class="description">${e[0].description}</p>
            <p><span class="temperament">Temperament:</span> ${e[0].temperament}</p>
        </div>
    `;o.divCatInfo.innerHTML=a,n(o.pLoader,!1),n(o.selectWraper,!0),n(o.divCatInfo,!0)}function f(){n(o.pLoader,!1),m.show({message:"Oops! Something went wrong! Try reloading the page!",messageColor:"white",backgroundColor:"tomato",timeout:4e3,position:"topCenter"})}function n(t,e){e?t.removeAttribute("hidden"):t.setAttribute("hidden","")}n(o.selectWraper,!1);n(o.divCatInfo,!1);y().then(t=>L(t)).catch(t=>f());function I(t){t[0].placeholder||(n(o.pLoader,!0),n(o.divCatInfo,!1),o.divCatInfo.innerHTML="",S(t[0].value).then(e=>w(e[0])).catch(e=>f()))}
//# sourceMappingURL=commonHelpers.js.map
